// Auto-generated by scripts/write-release-config.mjs
// Do not edit by hand.

export const liveTApiBaseUrl = "https://api.live-t.invalid";
export const liveTWebBaseUrl = "https://app.live-t.invalid";
export const liveTDocumentationUrl = "https://github.com/athletica-one/live-t-n8n#credentials";
